require "DO/DO_ClientNetwork"
require "DO/Markers/DO_MapSymbolDefinitions"
require "DO/Markers/DO_ZombieTargetResolver"
require "DO/Markers/DO_MapMarkerSystem"
require "DO/Markers/DO_WorldMarkerSystem"
require "DO/Markers/DO_ZombieClearIndicatorSystem"
require "DO/UI/DO_MissionModalShared"
require "DO/UI/DO_CompletionModal"
require "DO/UI/DO_FailureModal"
require "DO/UI/DO_ProgressModal"
require "DO/UI/DO_MissionViewerWindow"
require "DO/UI/DO_ObjectiveHUD"
require "DO/UI/DO_QuestManagerWindow"
require "DO/UI/Debug/DO_DebugWindow"
require "DO/UI/Debug/DO_DebugInit"

DynamicObjectives.Log("Init", "Client", "Client bootstrap loaded")
